# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\Coursework 5\UI Files\AddConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddConfirmation(object):
    def setupUi(self, AddConfirmation):
        AddConfirmation.setObjectName("AddConfirmation")
        AddConfirmation.resize(400, 185)
        AddConfirmation.setMinimumSize(QtCore.QSize(400, 185))
        AddConfirmation.setMaximumSize(QtCore.QSize(400, 185))
        self.pbAdd = QtWidgets.QPushButton(AddConfirmation)
        self.pbAdd.setGeometry(QtCore.QRect(310, 160, 81, 21))
        self.pbAdd.setObjectName("pbAdd")
        self.pbCancel = QtWidgets.QPushButton(AddConfirmation)
        self.pbCancel.setGeometry(QtCore.QRect(10, 160, 81, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.lblConfirmation = QtWidgets.QLabel(AddConfirmation)
        self.lblConfirmation.setGeometry(QtCore.QRect(10, 10, 381, 101))
        self.lblConfirmation.setText("")
        self.lblConfirmation.setObjectName("lblConfirmation")

        self.retranslateUi(AddConfirmation)
        QtCore.QMetaObject.connectSlotsByName(AddConfirmation)

    def retranslateUi(self, AddConfirmation):
        _translate = QtCore.QCoreApplication.translate
        AddConfirmation.setWindowTitle(_translate("AddConfirmation", "Dialog"))
        self.pbAdd.setText(_translate("AddConfirmation", "Add Item"))
        self.pbCancel.setText(_translate("AddConfirmation", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddConfirmation = QtWidgets.QDialog()
    ui = Ui_AddConfirmation()
    ui.setupUi(AddConfirmation)
    AddConfirmation.show()
    sys.exit(app.exec_())
