# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\OneDrive_2022-11-22\coursework 8\UI Files\AlterMenuItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlterMenuItem(object):
    def setupUi(self, AlterMenuItem):
        AlterMenuItem.setObjectName("AlterMenuItem")
        AlterMenuItem.resize(1067, 541)
        AlterMenuItem.setMinimumSize(QtCore.QSize(1067, 541))
        AlterMenuItem.setMaximumSize(QtCore.QSize(1067, 541))
        self.twMenuItems = QtWidgets.QTableWidget(AlterMenuItem)
        self.twMenuItems.setGeometry(QtCore.QRect(20, 50, 1021, 431))
        self.twMenuItems.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twMenuItems.setTabKeyNavigation(False)
        self.twMenuItems.setProperty("showDropIndicator", False)
        self.twMenuItems.setDragDropOverwriteMode(False)
        self.twMenuItems.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twMenuItems.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twMenuItems.setObjectName("twMenuItems")
        self.twMenuItems.setColumnCount(0)
        self.twMenuItems.setRowCount(0)
        self.pbBack = QtWidgets.QPushButton(AlterMenuItem)
        self.pbBack.setGeometry(QtCore.QRect(920, 10, 121, 31))
        self.pbBack.setObjectName("pbBack")

        self.retranslateUi(AlterMenuItem)
        QtCore.QMetaObject.connectSlotsByName(AlterMenuItem)

    def retranslateUi(self, AlterMenuItem):
        _translate = QtCore.QCoreApplication.translate
        AlterMenuItem.setWindowTitle(_translate("AlterMenuItem", "Dialog"))
        self.pbBack.setText(_translate("AlterMenuItem", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlterMenuItem = QtWidgets.QDialog()
    ui = Ui_AlterMenuItem()
    ui.setupUi(AlterMenuItem)
    AlterMenuItem.show()
    sys.exit(app.exec_())
