# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\AlterItemConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlterConfirmation(object):
    def setupUi(self, AlterConfirmation):
        AlterConfirmation.setObjectName("AlterConfirmation")
        AlterConfirmation.resize(643, 286)
        AlterConfirmation.setMinimumSize(QtCore.QSize(643, 286))
        AlterConfirmation.setMaximumSize(QtCore.QSize(643, 286))
        self.pbAlter = QtWidgets.QPushButton(AlterConfirmation)
        self.pbAlter.setGeometry(QtCore.QRect(540, 250, 91, 31))
        self.pbAlter.setObjectName("pbAlter")
        self.pbCancel = QtWidgets.QPushButton(AlterConfirmation)
        self.pbCancel.setGeometry(QtCore.QRect(10, 250, 91, 31))
        self.pbCancel.setObjectName("pbCancel")
        self.leItemname = QtWidgets.QLineEdit(AlterConfirmation)
        self.leItemname.setGeometry(QtCore.QRect(10, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leItemname.setFont(font)
        self.leItemname.setStyleSheet("")
        self.leItemname.setObjectName("leItemname")
        self.lblitemdetails = QtWidgets.QLabel(AlterConfirmation)
        self.lblitemdetails.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblitemdetails.setFont(font)
        self.lblitemdetails.setStyleSheet("")
        self.lblitemdetails.setObjectName("lblitemdetails")
        self.cbCategory = QtWidgets.QComboBox(AlterConfirmation)
        self.cbCategory.setGeometry(QtCore.QRect(10, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbCategory.setFont(font)
        self.cbCategory.setStyleSheet("")
        self.cbCategory.setObjectName("cbCategory")
        self.cbCategory.addItem("")
        self.cbCategory.addItem("")
        self.cbCategory.addItem("")
        self.cbCategory.addItem("")
        self.sbPrice = QtWidgets.QDoubleSpinBox(AlterConfirmation)
        self.sbPrice.setGeometry(QtCore.QRect(100, 181, 62, 31))
        self.sbPrice.setMinimum(0.0)
        self.sbPrice.setMaximum(250.0)
        self.sbPrice.setProperty("value", 9.99)
        self.sbPrice.setObjectName("sbPrice")
        self.lblItemPrice = QtWidgets.QLabel(AlterConfirmation)
        self.lblItemPrice.setGeometry(QtCore.QRect(10, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblItemPrice.setFont(font)
        self.lblItemPrice.setStyleSheet("")
        self.lblItemPrice.setObjectName("lblItemPrice")
        self.lblErrorItemName = QtWidgets.QLabel(AlterConfirmation)
        self.lblErrorItemName.setGeometry(QtCore.QRect(10, 90, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblErrorItemName.setFont(font)
        self.lblErrorItemName.setText("")
        self.lblErrorItemName.setObjectName("lblErrorItemName")
        self.lblErrorCategory = QtWidgets.QLabel(AlterConfirmation)
        self.lblErrorCategory.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblErrorCategory.setFont(font)
        self.lblErrorCategory.setText("")
        self.lblErrorCategory.setObjectName("lblErrorCategory")

        self.retranslateUi(AlterConfirmation)
        QtCore.QMetaObject.connectSlotsByName(AlterConfirmation)

    def retranslateUi(self, AlterConfirmation):
        _translate = QtCore.QCoreApplication.translate
        AlterConfirmation.setWindowTitle(_translate("AlterConfirmation", "Dialog"))
        self.pbAlter.setText(_translate("AlterConfirmation", "Alter Item"))
        self.pbCancel.setText(_translate("AlterConfirmation", "Cancel"))
        self.leItemname.setPlaceholderText(_translate("AlterConfirmation", "Item Name"))
        self.lblitemdetails.setText(_translate("AlterConfirmation", "Enter Item Details:"))
        self.cbCategory.setCurrentText(_translate("AlterConfirmation", "Starter"))
        self.cbCategory.setItemText(0, _translate("AlterConfirmation", "Starter"))
        self.cbCategory.setItemText(1, _translate("AlterConfirmation", "Main"))
        self.cbCategory.setItemText(2, _translate("AlterConfirmation", "Dessert"))
        self.cbCategory.setItemText(3, _translate("AlterConfirmation", "Drink"))
        self.lblItemPrice.setText(_translate("AlterConfirmation", "Item Price:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlterConfirmation = QtWidgets.QDialog()
    ui = Ui_AlterConfirmation()
    ui.setupUi(AlterConfirmation)
    AlterConfirmation.show()
    sys.exit(app.exec_())
