# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\Coursework 5\UI Files\BookingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Booking(object):
    def setupUi(self, Booking):
        Booking.setObjectName("Booking")
        Booking.resize(1067, 541)
        Booking.setMinimumSize(QtCore.QSize(1067, 541))
        Booking.setMaximumSize(QtCore.QSize(1067, 541))
        self.BookingWidget = QtWidgets.QStackedWidget(Booking)
        self.BookingWidget.setGeometry(QtCore.QRect(0, 60, 1067, 481))
        self.BookingWidget.setObjectName("BookingWidget")
        self.frame = QtWidgets.QFrame(Booking)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1067, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pbDate = QtWidgets.QPushButton(self.frame)
        self.pbDate.setGeometry(QtCore.QRect(10, 10, 201, 51))
        self.pbDate.setObjectName("pbDate")
        self.pbSize = QtWidgets.QPushButton(self.frame)
        self.pbSize.setEnabled(False)
        self.pbSize.setGeometry(QtCore.QRect(220, 10, 201, 51))
        self.pbSize.setStyleSheet("pbSize.setEnabled(False)")
        self.pbSize.setObjectName("pbSize")
        self.pbTime = QtWidgets.QPushButton(self.frame)
        self.pbTime.setEnabled(False)
        self.pbTime.setGeometry(QtCore.QRect(430, 10, 201, 51))
        self.pbTime.setObjectName("pbTime")
        self.pbTable = QtWidgets.QPushButton(self.frame)
        self.pbTable.setEnabled(False)
        self.pbTable.setGeometry(QtCore.QRect(640, 10, 201, 51))
        self.pbTable.setObjectName("pbTable")
        self.pbGuest = QtWidgets.QPushButton(self.frame)
        self.pbGuest.setEnabled(False)
        self.pbGuest.setGeometry(QtCore.QRect(850, 10, 201, 51))
        self.pbGuest.setObjectName("pbGuest")

        self.retranslateUi(Booking)
        self.BookingWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Booking)

    def retranslateUi(self, Booking):
        _translate = QtCore.QCoreApplication.translate
        Booking.setWindowTitle(_translate("Booking", "Dialog"))
        self.pbDate.setText(_translate("Booking", "Date"))
        self.pbSize.setText(_translate("Booking", "Party Size"))
        self.pbTime.setText(_translate("Booking", "Time"))
        self.pbTable.setText(_translate("Booking", "Table"))
        self.pbGuest.setText(_translate("Booking", "Guest"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Booking = QtWidgets.QDialog()
    ui = Ui_Booking()
    ui.setupUi(Booking)
    Booking.show()
    sys.exit(app.exec_())
