# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(1067, 541)
        Calendar.setMinimumSize(QtCore.QSize(1067, 541))
        Calendar.setMaximumSize(QtCore.QSize(1067, 541))
        self.cwCalendar = QtWidgets.QCalendarWidget(Calendar)
        self.cwCalendar.setGeometry(QtCore.QRect(10, 20, 551, 511))
        self.cwCalendar.setStyleSheet("")
        self.cwCalendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.LongDayNames)
        self.cwCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.cwCalendar.setObjectName("cwCalendar")
        self.twReservations = QtWidgets.QTableWidget(Calendar)
        self.twReservations.setGeometry(QtCore.QRect(580, 20, 481, 511))
        self.twReservations.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twReservations.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twReservations.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twReservations.setObjectName("twReservations")
        self.twReservations.setColumnCount(0)
        self.twReservations.setRowCount(0)
        self.label = QtWidgets.QLabel(Calendar)
        self.label.setGeometry(QtCore.QRect(580, 0, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Dialog"))
        self.label.setText(_translate("Calendar", "Double Click on Reservation to Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calendar = QtWidgets.QDialog()
    ui = Ui_Calendar()
    ui.setupUi(Calendar)
    Calendar.show()
    sys.exit(app.exec_())
