# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\OneDrive_2022-11-22\coursework 8\UI Files\ChangeQuantity.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeQuantity(object):
    def setupUi(self, ChangeQuantity):
        ChangeQuantity.setObjectName("ChangeQuantity")
        ChangeQuantity.resize(400, 185)
        ChangeQuantity.setMinimumSize(QtCore.QSize(400, 185))
        ChangeQuantity.setMaximumSize(QtCore.QSize(400, 185))
        self.pbChange = QtWidgets.QPushButton(ChangeQuantity)
        self.pbChange.setGeometry(QtCore.QRect(300, 160, 91, 21))
        self.pbChange.setObjectName("pbChange")
        self.pbCancel = QtWidgets.QPushButton(ChangeQuantity)
        self.pbCancel.setGeometry(QtCore.QRect(10, 160, 81, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.lblItem = QtWidgets.QLabel(ChangeQuantity)
        self.lblItem.setGeometry(QtCore.QRect(10, 40, 381, 31))
        self.lblItem.setText("")
        self.lblItem.setObjectName("lblItem")
        self.lblItem_2 = QtWidgets.QLabel(ChangeQuantity)
        self.lblItem_2.setGeometry(QtCore.QRect(10, 80, 51, 41))
        self.lblItem_2.setObjectName("lblItem_2")
        self.sbQuantity = QtWidgets.QSpinBox(ChangeQuantity)
        self.sbQuantity.setGeometry(QtCore.QRect(70, 90, 42, 21))
        self.sbQuantity.setMaximum(30)
        self.sbQuantity.setObjectName("sbQuantity")

        self.retranslateUi(ChangeQuantity)
        QtCore.QMetaObject.connectSlotsByName(ChangeQuantity)

    def retranslateUi(self, ChangeQuantity):
        _translate = QtCore.QCoreApplication.translate
        ChangeQuantity.setWindowTitle(_translate("ChangeQuantity", "Dialog"))
        self.pbChange.setText(_translate("ChangeQuantity", "Change Quantity"))
        self.pbCancel.setText(_translate("ChangeQuantity", "Cancel"))
        self.lblItem_2.setText(_translate("ChangeQuantity", "Quantity:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangeQuantity = QtWidgets.QDialog()
    ui = Ui_ChangeQuantity()
    ui.setupUi(ChangeQuantity)
    ChangeQuantity.show()
    sys.exit(app.exec_())
