# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\Coursework 5\UI Files\CloseTableConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CloseConfirmation(object):
    def setupUi(self, CloseConfirmation):
        CloseConfirmation.setObjectName("CloseConfirmation")
        CloseConfirmation.resize(400, 185)
        CloseConfirmation.setMinimumSize(QtCore.QSize(400, 185))
        CloseConfirmation.setMaximumSize(QtCore.QSize(400, 185))
        self.lblConfirmation = QtWidgets.QLabel(CloseConfirmation)
        self.lblConfirmation.setGeometry(QtCore.QRect(10, 50, 381, 61))
        self.lblConfirmation.setText("")
        self.lblConfirmation.setObjectName("lblConfirmation")
        self.pbCancel = QtWidgets.QPushButton(CloseConfirmation)
        self.pbCancel.setGeometry(QtCore.QRect(10, 160, 81, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbClose = QtWidgets.QPushButton(CloseConfirmation)
        self.pbClose.setGeometry(QtCore.QRect(310, 160, 81, 21))
        self.pbClose.setObjectName("pbClose")

        self.retranslateUi(CloseConfirmation)
        QtCore.QMetaObject.connectSlotsByName(CloseConfirmation)

    def retranslateUi(self, CloseConfirmation):
        _translate = QtCore.QCoreApplication.translate
        CloseConfirmation.setWindowTitle(_translate("CloseConfirmation", "Dialog"))
        self.pbCancel.setText(_translate("CloseConfirmation", "Cancel"))
        self.pbClose.setText(_translate("CloseConfirmation", "Close Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CloseConfirmation = QtWidgets.QDialog()
    ui = Ui_CloseConfirmation()
    ui.setupUi(CloseConfirmation)
    CloseConfirmation.show()
    sys.exit(app.exec_())
