# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\OneDrive_2022-11-22\coursework 9\UI Files\DateSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Date(object):
    def setupUi(self, Date):
        Date.setObjectName("Date")
        Date.resize(1067, 481)
        self.cwCalendar = QtWidgets.QCalendarWidget(Date)
        self.cwCalendar.setGeometry(QtCore.QRect(30, 10, 1001, 461))
        self.cwCalendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.LongDayNames)
        self.cwCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.cwCalendar.setObjectName("cwCalendar")

        self.retranslateUi(Date)
        QtCore.QMetaObject.connectSlotsByName(Date)

    def retranslateUi(self, Date):
        _translate = QtCore.QCoreApplication.translate
        Date.setWindowTitle(_translate("Date", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Date = QtWidgets.QDialog()
    ui = Ui_Date()
    ui.setupUi(Date)
    Date.show()
    sys.exit(app.exec_())
