# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\21heffernajn42\Downloads\Coursework (1)\UI Files\DessertsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DessertsPage(object):
    def setupUi(self, DessertsPage):
        DessertsPage.setObjectName("DessertsPage")
        DessertsPage.resize(647, 421)

        self.retranslateUi(DessertsPage)
        QtCore.QMetaObject.connectSlotsByName(DessertsPage)

    def retranslateUi(self, DessertsPage):
        _translate = QtCore.QCoreApplication.translate
        DessertsPage.setWindowTitle(_translate("DessertsPage", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DessertsPage = QtWidgets.QDialog()
    ui = Ui_DessertsPage()
    ui.setupUi(DessertsPage)
    DessertsPage.show()
    sys.exit(app.exec_())
