# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\21heffernajn42\Downloads\Coursework (1)\UI Files\DrinksPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DrinksPage(object):
    def setupUi(self, DrinksPage):
        DrinksPage.setObjectName("DrinksPage")
        DrinksPage.resize(647, 421)

        self.retranslateUi(DrinksPage)
        QtCore.QMetaObject.connectSlotsByName(DrinksPage)

    def retranslateUi(self, DrinksPage):
        _translate = QtCore.QCoreApplication.translate
        DrinksPage.setWindowTitle(_translate("DrinksPage", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrinksPage = QtWidgets.QDialog()
    ui = Ui_DrinksPage()
    ui.setupUi(DrinksPage)
    DrinksPage.show()
    sys.exit(app.exec_())
