# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\OneDrive_2022-10-03\Coursework (1)121\UI Files\EditMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditMenu(object):
    def setupUi(self, EditMenu):
        EditMenu.setObjectName("EditMenu")
        EditMenu.resize(1067, 541)
        EditMenu.setMinimumSize(QtCore.QSize(1067, 541))
        EditMenu.setMaximumSize(QtCore.QSize(1067, 541))
        self.pbAddItem = QtWidgets.QPushButton(EditMenu)
        self.pbAddItem.setGeometry(QtCore.QRect(10, 10, 521, 251))
        self.pbAddItem.setObjectName("pbAddItem")
        self.pbAddItem.setStyleSheet('font: 12pt "MS Shell Dlg 2";')
        self.pbRemoveItem = QtWidgets.QPushButton(EditMenu)
        self.pbRemoveItem.setGeometry(QtCore.QRect(540, 10, 521, 251))
        self.pbRemoveItem.setObjectName("pbRemoveItem")
        self.pbRemoveItem.setStyleSheet('font: 12pt "MS Shell Dlg 2";')
        self.pbAlterItem = QtWidgets.QPushButton(EditMenu)
        self.pbAlterItem.setGeometry(QtCore.QRect(10, 270, 521, 251))
        self.pbAlterItem.setObjectName("pbAlterItem")
        self.pbAlterItem.setStyleSheet('font: 12pt "MS Shell Dlg 2";')

        self.retranslateUi(EditMenu)
        QtCore.QMetaObject.connectSlotsByName(EditMenu)

    def retranslateUi(self, EditMenu):
        _translate = QtCore.QCoreApplication.translate
        EditMenu.setWindowTitle(_translate("EditMenu", "Dialog"))
        self.pbAddItem.setText(_translate("EditMenu", "Add Item"))
        self.pbRemoveItem.setText(_translate("EditMenu", "Remove Item"))
        self.pbAlterItem.setText(_translate("EditMenu", "Alter Item"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditMenu = QtWidgets.QDialog()
    ui = Ui_EditMenu()
    ui.setupUi(EditMenu)
    EditMenu.show()
    sys.exit(app.exec_())
