# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(786, 470)
        self.lePassword = QtWidgets.QLineEdit(LoginPage)
        self.lePassword.setGeometry(QtCore.QRect(276, 90, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.lePassword.setFont(font)
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lePassword.setReadOnly(True)
        self.lePassword.setObjectName("lePassword")
        self.lblError = QtWidgets.QLabel(LoginPage)
        self.lblError.setGeometry(QtCore.QRect(276, 150, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblError.setFont(font)
        self.lblError.setStyleSheet("color: rgb(170, 0, 0);")
        self.lblError.setText("")
        self.lblError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblError.setObjectName("lblError")

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QDialog()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
