# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\21heffernajn42\Downloads\Coursework (1)\UI Files\MainsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainsPage(object):
    def setupUi(self, MainsPage):
        MainsPage.setObjectName("MainsPage")
        MainsPage.resize(647, 421)

        self.retranslateUi(MainsPage)
        QtCore.QMetaObject.connectSlotsByName(MainsPage)

    def retranslateUi(self, MainsPage):
        _translate = QtCore.QCoreApplication.translate
        MainsPage.setWindowTitle(_translate("MainsPage", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainsPage = QtWidgets.QDialog()
    ui = Ui_MainsPage()
    ui.setupUi(MainsPage)
    MainsPage.show()
    sys.exit(app.exec_())
