# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\ManagementScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Management(object):
    def setupUi(self, Management):
        Management.setObjectName("Management")
        Management.resize(1067, 541)
        Management.setMinimumSize(QtCore.QSize(1067, 541))
        Management.setMaximumSize(QtCore.QSize(1067, 541))
        self.pbEditMenu = QtWidgets.QPushButton(Management)
        self.pbEditMenu.setGeometry(QtCore.QRect(10, 10, 511, 241))
        self.pbEditMenu.setObjectName("pbEditMenu")
        self.pbStaff = QtWidgets.QPushButton(Management)
        self.pbStaff.setGeometry(QtCore.QRect(540, 10, 511, 241))
        self.pbStaff.setObjectName("pbStaff")
        self.pbStatistics = QtWidgets.QPushButton(Management)
        self.pbStatistics.setGeometry(QtCore.QRect(10, 270, 1041, 241))
        self.pbStatistics.setObjectName("pbStatistics")

        self.retranslateUi(Management)
        QtCore.QMetaObject.connectSlotsByName(Management)

    def retranslateUi(self, Management):
        _translate = QtCore.QCoreApplication.translate
        Management.setWindowTitle(_translate("Management", "Dialog"))
        self.pbEditMenu.setText(_translate("Management", "Edit Menu"))
        self.pbStaff.setText(_translate("Management", "Edit Staff Passwords"))
        self.pbStatistics.setText(_translate("Management", "Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Management = QtWidgets.QDialog()
    ui = Ui_Management()
    ui.setupUi(Management)
    Management.show()
    sys.exit(app.exec_())
