# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\OrderScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderScreen(object):
    def setupUi(self, OrderScreen):
        OrderScreen.setObjectName("OrderScreen")
        OrderScreen.resize(1067, 541)
        OrderScreen.setMinimumSize(QtCore.QSize(1067, 541))
        OrderScreen.setMaximumSize(QtCore.QSize(1067, 541))
        self.pbStarter = QtWidgets.QPushButton(OrderScreen)
        self.pbStarter.setGeometry(QtCore.QRect(0, 320, 211, 91))
        self.pbStarter.setObjectName("pbStarter")
        self.pbMain = QtWidgets.QPushButton(OrderScreen)
        self.pbMain.setGeometry(QtCore.QRect(210, 320, 211, 91))
        self.pbMain.setObjectName("pbMain")
        self.pbDrinks = QtWidgets.QPushButton(OrderScreen)
        self.pbDrinks.setGeometry(QtCore.QRect(210, 410, 211, 91))
        self.pbDrinks.setObjectName("pbDrinks")
        self.pbDesserts = QtWidgets.QPushButton(OrderScreen)
        self.pbDesserts.setGeometry(QtCore.QRect(0, 410, 211, 91))
        self.pbDesserts.setObjectName("pbDesserts")
        self.pbConfirm = QtWidgets.QPushButton(OrderScreen)
        self.pbConfirm.setGeometry(QtCore.QRect(0, 500, 211, 41))
        self.pbConfirm.setObjectName("pbConfirm")
        self.lblTotal = QtWidgets.QLabel(OrderScreen)
        self.lblTotal.setGeometry(QtCore.QRect(0, 40, 421, 41))
        self.lblTotal.setObjectName("lblTotal")
        self.pbClose = QtWidgets.QPushButton(OrderScreen)
        self.pbClose.setGeometry(QtCore.QRect(850, 500, 217, 41))
        self.pbClose.setObjectName("pbClose")
        self.pbExit = QtWidgets.QPushButton(OrderScreen)
        self.pbExit.setGeometry(QtCore.QRect(1006, 0, 61, 41))
        self.pbExit.setObjectName("pbExit")
        self.orderwidget = QtWidgets.QStackedWidget(OrderScreen)
        self.orderwidget.setGeometry(QtCore.QRect(420, 80, 647, 421))
        self.orderwidget.setObjectName("orderwidget")
        self.lblTable = QtWidgets.QLabel(OrderScreen)
        self.lblTable.setGeometry(QtCore.QRect(0, 2, 421, 41))
        self.lblTable.setObjectName("lblTable")
        self.twOrders = QtWidgets.QTableWidget(OrderScreen)
        self.twOrders.setGeometry(QtCore.QRect(0, 80, 421, 241))
        self.twOrders.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twOrders.setTabKeyNavigation(False)
        self.twOrders.setProperty("showDropIndicator", False)
        self.twOrders.setDragDropOverwriteMode(False)
        self.twOrders.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twOrders.setObjectName("twOrders")
        self.twOrders.setColumnCount(3)
        self.twOrders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twOrders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twOrders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twOrders.setHorizontalHeaderItem(2, item)
        self.twOrders.verticalHeader().setVisible(False)

        self.retranslateUi(OrderScreen)
        QtCore.QMetaObject.connectSlotsByName(OrderScreen)

    def retranslateUi(self, OrderScreen):
        _translate = QtCore.QCoreApplication.translate
        OrderScreen.setWindowTitle(_translate("OrderScreen", "Dialog"))
        self.pbStarter.setText(_translate("OrderScreen", "Starters"))
        self.pbMain.setText(_translate("OrderScreen", "Mains"))
        self.pbDrinks.setText(_translate("OrderScreen", "Drinks"))
        self.pbDesserts.setText(_translate("OrderScreen", "Desserts"))
        self.pbConfirm.setText(_translate("OrderScreen", "Confirm"))
        self.lblTotal.setText(_translate("OrderScreen", "Total"))
        self.pbClose.setText(_translate("OrderScreen", "Close Table"))
        self.pbExit.setText(_translate("OrderScreen", "Exit"))
        self.lblTable.setText(_translate("OrderScreen", "Table"))
        item = self.twOrders.horizontalHeaderItem(0)
        item.setText(_translate("OrderScreen", "Item Name"))
        item = self.twOrders.horizontalHeaderItem(1)
        item.setText(_translate("OrderScreen", "Quantity"))
        item = self.twOrders.horizontalHeaderItem(2)
        item.setText(_translate("OrderScreen", "Price"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderScreen = QtWidgets.QDialog()
    ui = Ui_OrderScreen()
    ui.setupUi(OrderScreen)
    OrderScreen.show()
    sys.exit(app.exec_())
