# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\PartySizeSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PartySize(object):
    def setupUi(self, PartySize):
        PartySize.setObjectName("PartySize")
        PartySize.resize(1067, 481)
        self.lwSize = QtWidgets.QListWidget(PartySize)
        self.lwSize.setGeometry(QtCore.QRect(320, 40, 421, 401))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lwSize.setFont(font)
        self.lwSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lwSize.setAutoFillBackground(False)
        self.lwSize.setLineWidth(1)
        self.lwSize.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lwSize.setIconSize(QtCore.QSize(0, 0))
        self.lwSize.setFlow(QtWidgets.QListView.TopToBottom)
        self.lwSize.setResizeMode(QtWidgets.QListView.Fixed)
        self.lwSize.setGridSize(QtCore.QSize(0, 49))
        self.lwSize.setViewMode(QtWidgets.QListView.ListMode)
        self.lwSize.setWordWrap(False)
        self.lwSize.setObjectName("lwSize")
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwSize.addItem(item)
        self.cbCustom = QtWidgets.QCheckBox(PartySize)
        self.cbCustom.setGeometry(QtCore.QRect(1030, 40, 31, 31))
        self.cbCustom.setText("")
        self.cbCustom.setIconSize(QtCore.QSize(16, 16))
        self.cbCustom.setObjectName("cbCustom")
        self.lblCustom = QtWidgets.QLabel(PartySize)
        self.lblCustom.setGeometry(QtCore.QRect(900, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lblCustom.setFont(font)
        self.lblCustom.setObjectName("lblCustom")
        self.sbCustom = QtWidgets.QSpinBox(PartySize)
        self.sbCustom.setGeometry(QtCore.QRect(1001, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sbCustom.setFont(font)
        self.sbCustom.setMinimum(9)
        self.sbCustom.setMaximum(20)
        self.sbCustom.setObjectName("sbCustom")

        self.retranslateUi(PartySize)
        QtCore.QMetaObject.connectSlotsByName(PartySize)

    def retranslateUi(self, PartySize):
        _translate = QtCore.QCoreApplication.translate
        PartySize.setWindowTitle(_translate("PartySize", "Dialog"))
        __sortingEnabled = self.lwSize.isSortingEnabled()
        self.lwSize.setSortingEnabled(False)
        item = self.lwSize.item(0)
        item.setText(_translate("PartySize", "1 Guest"))
        item = self.lwSize.item(1)
        item.setText(_translate("PartySize", "2 Guests"))
        item = self.lwSize.item(2)
        item.setText(_translate("PartySize", "3 Guests"))
        item = self.lwSize.item(3)
        item.setText(_translate("PartySize", "4 Guests"))
        item = self.lwSize.item(4)
        item.setText(_translate("PartySize", "5 Guests"))
        item = self.lwSize.item(5)
        item.setText(_translate("PartySize", "6 Guests"))
        item = self.lwSize.item(6)
        item.setText(_translate("PartySize", "7 Guests"))
        item = self.lwSize.item(7)
        item.setText(_translate("PartySize", "8 Guests"))
        self.lwSize.setSortingEnabled(__sortingEnabled)
        self.lblCustom.setText(_translate("PartySize", "Custom Amount"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PartySize = QtWidgets.QDialog()
    ui = Ui_PartySize()
    ui.setupUi(PartySize)
    PartySize.show()
    sys.exit(app.exec_())
