# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\OneDrive_2022-10-03\Coursework (1)121\UI Files\RemoveConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Confirmation(object):
    def setupUi(self, Confirmation):
        Confirmation.setObjectName("Confirmation")
        Confirmation.resize(400, 185)
        self.pbRemove = QtWidgets.QPushButton(Confirmation)
        self.pbRemove.setGeometry(QtCore.QRect(310, 160, 81, 21))
        self.pbRemove.setObjectName("pbRemove")
        self.pbCancel = QtWidgets.QPushButton(Confirmation)
        self.pbCancel.setGeometry(QtCore.QRect(10, 160, 81, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.lblConfirmation = QtWidgets.QLabel(Confirmation)
        self.lblConfirmation.setGeometry(QtCore.QRect(10, 50, 381, 61))
        self.lblConfirmation.setText("")
        self.lblConfirmation.setObjectName("lblConfirmation")

        self.retranslateUi(Confirmation)
        QtCore.QMetaObject.connectSlotsByName(Confirmation)

    def retranslateUi(self, Confirmation):
        _translate = QtCore.QCoreApplication.translate
        Confirmation.setWindowTitle(_translate("Confirmation", "Dialog"))
        self.pbRemove.setText(_translate("Confirmation", "Remove Item"))
        self.pbCancel.setText(_translate("Confirmation", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Confirmation = QtWidgets.QDialog()
    ui = Ui_Confirmation()
    ui.setupUi(Confirmation)
    Confirmation.show()
    sys.exit(app.exec_())
