# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\RemoveMenuItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoveMenuItem(object):
    def setupUi(self, RemoveMenuItem):
        RemoveMenuItem.setObjectName("RemoveMenuItem")
        RemoveMenuItem.resize(1067, 541)
        RemoveMenuItem.setMinimumSize(QtCore.QSize(1067, 541))
        RemoveMenuItem.setMaximumSize(QtCore.QSize(1067, 541))
        self.twMenuItems = QtWidgets.QTableWidget(RemoveMenuItem)
        self.twMenuItems.setGeometry(QtCore.QRect(20, 50, 1021, 431))
        self.twMenuItems.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twMenuItems.setTabKeyNavigation(False)
        self.twMenuItems.setProperty("showDropIndicator", False)
        self.twMenuItems.setDragDropOverwriteMode(False)
        self.twMenuItems.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twMenuItems.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twMenuItems.setObjectName("twMenuItems")
        self.twMenuItems.setColumnCount(0)
        self.twMenuItems.setRowCount(0)
        self.pbBack = QtWidgets.QPushButton(RemoveMenuItem)
        self.pbBack.setGeometry(QtCore.QRect(920, 10, 121, 31))
        self.pbBack.setObjectName("pbBack")
        self.pbRemoveItem = QtWidgets.QPushButton(RemoveMenuItem)
        self.pbRemoveItem.setGeometry(QtCore.QRect(920, 490, 121, 41))
        self.pbRemoveItem.setObjectName("pbRemoveItem")
        self.lblError = QtWidgets.QLabel(RemoveMenuItem)
        self.lblError.setGeometry(QtCore.QRect(20, 490, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblError.setFont(font)
        self.lblError.setText("")
        self.lblError.setObjectName("lblError")

        self.retranslateUi(RemoveMenuItem)
        QtCore.QMetaObject.connectSlotsByName(RemoveMenuItem)

    def retranslateUi(self, RemoveMenuItem):
        _translate = QtCore.QCoreApplication.translate
        RemoveMenuItem.setWindowTitle(_translate("RemoveMenuItem", "Dialog"))
        self.pbBack.setText(_translate("RemoveMenuItem", "Back"))
        self.pbRemoveItem.setText(_translate("RemoveMenuItem", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemoveMenuItem = QtWidgets.QDialog()
    ui = Ui_RemoveMenuItem()
    ui.setupUi(RemoveMenuItem)
    RemoveMenuItem.show()
    sys.exit(app.exec_())
