# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\RemoveBooking.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoveBooking(object):
    def setupUi(self, RemoveBooking):
        RemoveBooking.setObjectName("RemoveBooking")
        RemoveBooking.resize(400, 185)
        RemoveBooking.setMinimumSize(QtCore.QSize(400, 185))
        RemoveBooking.setMaximumSize(QtCore.QSize(400, 185))
        self.pbRemove = QtWidgets.QPushButton(RemoveBooking)
        self.pbRemove.setGeometry(QtCore.QRect(300, 150, 91, 31))
        self.pbRemove.setObjectName("pbRemove")
        self.pbCancel = QtWidgets.QPushButton(RemoveBooking)
        self.pbCancel.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.pbCancel.setObjectName("pbCancel")
        self.lblConfirmation = QtWidgets.QLabel(RemoveBooking)
        self.lblConfirmation.setGeometry(QtCore.QRect(10, 10, 381, 131))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblConfirmation.setFont(font)
        self.lblConfirmation.setText("")
        self.lblConfirmation.setObjectName("lblConfirmation")

        self.retranslateUi(RemoveBooking)
        QtCore.QMetaObject.connectSlotsByName(RemoveBooking)

    def retranslateUi(self, RemoveBooking):
        _translate = QtCore.QCoreApplication.translate
        RemoveBooking.setWindowTitle(_translate("RemoveBooking", "Dialog"))
        self.pbRemove.setText(_translate("RemoveBooking", "Remove Booking"))
        self.pbCancel.setText(_translate("RemoveBooking", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemoveBooking = QtWidgets.QDialog()
    ui = Ui_RemoveBooking()
    ui.setupUi(RemoveBooking)
    RemoveBooking.show()
    sys.exit(app.exec_())
