# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\Coursework\UI Files\Seating.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Seating(object):
    def setupUi(self, Seating):
        Seating.setObjectName("Seating")
        Seating.resize(1067, 541)
        Seating.setMinimumSize(QtCore.QSize(1067, 541))
        Seating.setMaximumSize(QtCore.QSize(1067, 541))

        self.retranslateUi(Seating)
        QtCore.QMetaObject.connectSlotsByName(Seating)

    def retranslateUi(self, Seating):
        _translate = QtCore.QCoreApplication.translate
        Seating.setWindowTitle(_translate("Seating", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Seating = QtWidgets.QDialog()
    ui = Ui_Seating()
    ui.setupUi(Seating)
    Seating.show()
    sys.exit(app.exec_())
