# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\Staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Staff(object):
    def setupUi(self, Staff):
        Staff.setObjectName("Staff")
        Staff.resize(1067, 541)
        Staff.setMinimumSize(QtCore.QSize(1067, 541))
        Staff.setMaximumSize(QtCore.QSize(1067, 541))
        Staff.setStyleSheet("")
        self.twStaff = QtWidgets.QTableWidget(Staff)
        self.twStaff.setGeometry(QtCore.QRect(310, 50, 751, 391))
        self.twStaff.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twStaff.setTabKeyNavigation(False)
        self.twStaff.setProperty("showDropIndicator", False)
        self.twStaff.setDragDropOverwriteMode(False)
        self.twStaff.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twStaff.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twStaff.setObjectName("twStaff")
        self.twStaff.setColumnCount(0)
        self.twStaff.setRowCount(0)
        self.leUserName = QtWidgets.QLineEdit(Staff)
        self.leUserName.setGeometry(QtCore.QRect(10, 140, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leUserName.setFont(font)
        self.leUserName.setStyleSheet("")
        self.leUserName.setObjectName("leUserName")
        self.pbConfirm = QtWidgets.QPushButton(Staff)
        self.pbConfirm.setGeometry(QtCore.QRect(910, 470, 141, 31))
        self.pbConfirm.setObjectName("pbConfirm")
        self.lblUserDetails = QtWidgets.QLabel(Staff)
        self.lblUserDetails.setGeometry(QtCore.QRect(10, 80, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblUserDetails.setFont(font)
        self.lblUserDetails.setStyleSheet("")
        self.lblUserDetails.setObjectName("lblUserDetails")
        self.lblItemPrice = QtWidgets.QLabel(Staff)
        self.lblItemPrice.setGeometry(QtCore.QRect(10, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblItemPrice.setFont(font)
        self.lblItemPrice.setStyleSheet("")
        self.lblItemPrice.setObjectName("lblItemPrice")
        self.lblErrorUserName = QtWidgets.QLabel(Staff)
        self.lblErrorUserName.setGeometry(QtCore.QRect(10, 170, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblErrorUserName.setFont(font)
        self.lblErrorUserName.setText("")
        self.lblErrorUserName.setObjectName("lblErrorUserName")
        self.lblErrorPassword = QtWidgets.QLabel(Staff)
        self.lblErrorPassword.setGeometry(QtCore.QRect(10, 250, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblErrorPassword.setFont(font)
        self.lblErrorPassword.setText("")
        self.lblErrorPassword.setObjectName("lblErrorPassword")
        self.lePassword = QtWidgets.QLineEdit(Staff)
        self.lePassword.setGeometry(QtCore.QRect(10, 220, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lePassword.setFont(font)
        self.lePassword.setStyleSheet("")
        self.lePassword.setObjectName("lePassword")
        self.cbManager = QtWidgets.QComboBox(Staff)
        self.cbManager.setGeometry(QtCore.QRect(80, 290, 69, 31))
        self.cbManager.setObjectName("cbManager")
        self.cbManager.addItem("")
        self.cbManager.addItem("")
        self.lblError = QtWidgets.QLabel(Staff)
        self.lblError.setGeometry(QtCore.QRect(780, 445, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblError.setFont(font)
        self.lblError.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblError.setStyleSheet("color: rgb(170, 0, 0);")
        self.lblError.setText("")
        self.lblError.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblError.setObjectName("lblError")

        self.retranslateUi(Staff)
        QtCore.QMetaObject.connectSlotsByName(Staff)

    def retranslateUi(self, Staff):
        _translate = QtCore.QCoreApplication.translate
        Staff.setWindowTitle(_translate("Staff", "Dialog"))
        self.leUserName.setPlaceholderText(_translate("Staff", "User Name"))
        self.pbConfirm.setText(_translate("Staff", "Confirm"))
        self.lblUserDetails.setText(_translate("Staff", "Alter User Details:"))
        self.lblItemPrice.setText(_translate("Staff", "Manager:"))
        self.lePassword.setPlaceholderText(_translate("Staff", "Password"))
        self.cbManager.setItemText(0, _translate("Staff", "No"))
        self.cbManager.setItemText(1, _translate("Staff", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Staff = QtWidgets.QDialog()
    ui = Ui_Staff()
    ui.setupUi(Staff)
    Staff.show()
    sys.exit(app.exec_())
