# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\OneDrive - The College of Richard Collyer\coursework 13\UI Files\Statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Statistics(object):
    def setupUi(self, Statistics):
        Statistics.setObjectName("Statistics")
        Statistics.resize(1067, 541)
        Statistics.setMinimumSize(QtCore.QSize(1067, 541))
        Statistics.setMaximumSize(QtCore.QSize(1067, 541))
        self.twStatistics = QtWidgets.QTableWidget(Statistics)
        self.twStatistics.setGeometry(QtCore.QRect(10, 60, 1041, 471))
        self.twStatistics.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twStatistics.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twStatistics.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twStatistics.setObjectName("twStatistics")
        self.twStatistics.setColumnCount(0)
        self.twStatistics.setRowCount(0)
        self.lblSort = QtWidgets.QLabel(Statistics)
        self.lblSort.setGeometry(QtCore.QRect(10, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblSort.setFont(font)
        self.lblSort.setObjectName("lblSort")
        self.cbSort = QtWidgets.QComboBox(Statistics)
        self.cbSort.setGeometry(QtCore.QRect(80, 21, 141, 31))
        self.cbSort.setObjectName("cbSort")
        self.cbSort.addItem("")
        self.cbSort.addItem("")

        self.retranslateUi(Statistics)
        QtCore.QMetaObject.connectSlotsByName(Statistics)

    def retranslateUi(self, Statistics):
        _translate = QtCore.QCoreApplication.translate
        Statistics.setWindowTitle(_translate("Statistics", "Dialog"))
        self.lblSort.setText(_translate("Statistics", "Sort By:"))
        self.cbSort.setItemText(0, _translate("Statistics", "Popularity (Ascending)"))
        self.cbSort.setItemText(1, _translate("Statistics", "Popularity (Descending)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Statistics = QtWidgets.QDialog()
    ui = Ui_Statistics()
    ui.setupUi(Statistics)
    Statistics.show()
    sys.exit(app.exec_())
