# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\Downloads\Coursework\UI Files\TimeSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Time(object):
    def setupUi(self, Time):
        Time.setObjectName("Time")
        Time.resize(1067, 481)
        self.lwTime = QtWidgets.QListWidget(Time)
        self.lwTime.setGeometry(QtCore.QRect(320, 40, 421, 401))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lwTime.setFont(font)
        self.lwTime.setAutoFillBackground(False)
        self.lwTime.setLineWidth(1)
        self.lwTime.setIconSize(QtCore.QSize(0, 0))
        self.lwTime.setFlow(QtWidgets.QListView.TopToBottom)
        self.lwTime.setResizeMode(QtWidgets.QListView.Fixed)
        self.lwTime.setGridSize(QtCore.QSize(0, 50))
        self.lwTime.setViewMode(QtWidgets.QListView.ListMode)
        self.lwTime.setWordWrap(False)
        self.lwTime.setObjectName("lwTime")
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwTime.addItem(item)

        self.retranslateUi(Time)
        QtCore.QMetaObject.connectSlotsByName(Time)

    def retranslateUi(self, Time):
        _translate = QtCore.QCoreApplication.translate
        Time.setWindowTitle(_translate("Time", "Dialog"))
        __sortingEnabled = self.lwTime.isSortingEnabled()
        self.lwTime.setSortingEnabled(False)
        item = self.lwTime.item(0)
        item.setText(_translate("Time", "12:00"))
        item = self.lwTime.item(1)
        item.setText(_translate("Time", "12:30"))
        item = self.lwTime.item(2)
        item.setText(_translate("Time", "13:00"))
        item = self.lwTime.item(3)
        item.setText(_translate("Time", "13:30"))
        item = self.lwTime.item(4)
        item.setText(_translate("Time", "14:00"))
        item = self.lwTime.item(5)
        item.setText(_translate("Time", "14:30"))
        item = self.lwTime.item(6)
        item.setText(_translate("Time", "15:00"))
        item = self.lwTime.item(7)
        item.setText(_translate("Time", "15:30"))
        item = self.lwTime.item(8)
        item.setText(_translate("Time", "16:00"))
        item = self.lwTime.item(9)
        item.setText(_translate("Time", "16:30"))
        item = self.lwTime.item(10)
        item.setText(_translate("Time", "17:00"))
        item = self.lwTime.item(11)
        item.setText(_translate("Time", "17:30"))
        item = self.lwTime.item(12)
        item.setText(_translate("Time", "18:00"))
        self.lwTime.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Time = QtWidgets.QDialog()
    ui = Ui_Time()
    ui.setupUi(Time)
    Time.show()
    sys.exit(app.exec_())
